version: "3"
services:
  db:
    image: postgres
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
  webapp:
    build: .
    container_name: webapp
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    links:
      - db
    command: sh entry.sh
